zeromq/dafka

- src/dafka_subscriber.c
> Problem: TODO out of data

- include/dafka_publisher.h
- include/dafka_store.h
- include/dafka_subscriber.h
- include/dafka_tower.h
- src/dafka_beacon.c
- src/dafka_beacon.h
- src/dafka_console_consumer.c
- src/dafka_publisher.c
- src/dafka_store.c
- src/dafka_subscriber.c
- src/dafka_tower.c
Solution: Deprecate the verbose command and set the verbose flag always
through the config
> Problem: verbose flag cannot be set by config

- src/dafka_publisher.c
Solution: Use the actual returned value
> Problem: head sequence is wrongfully assigned to pointer

- LICENSE
- README.md
- README.txt
Solution: Copy the Readme skeleton from czmq
> Problem: Dafka has no Readme

- src/dafka_publisher.c
- src/dafka_store.c
- src/dafka_subscriber.c
> Problem: wrong config value crashed tests

- src/dafka_store.c
Solution: whenever the store recognize a gap it should request the messages
> Problem: store is not requesting missing messages

- .travis.yml
Solution: make version clone the recent repository
> Problem: travis is using old version of czmq

- src/dafka_publisher.c
> Problem: we are destroying the wrong value

- .travis.yml
- CMakeLists.txt
- Makefile.am
- include/Makefile.am
- include/dafka_library.h
- project.xml
- src/Makemodule.am
- src/dafka_beacon.c
- src/dafka_beacon.h
- src/dafka_classes.h
- src/dafka_proto.c
- src/dafka_publisher.c
- src/dafka_selftest.c
- src/dafka_store.c
- src/dafka_subscriber.c
- src/dafka_tower.c
- src/dafka_util.c
- src/dafka_util.h
> Problem: CI is failing

- src/dafka_publisher.c
Solution: Do an explicit conversion
> Problem: Implicit conversion from 'void *' to 'dafka_proto_t *

- include/dafka.h
- src/dafka_beacon.c
- src/dafka_consumer.c
- src/dafka_perf_store.c
- src/dafka_producer.c
- src/dafka_store.c
Solution: don't wait for the OK signal
Lets wait to see if the CI is passing now
>  Problem: beacon is dropping CONNECT messages when waiting for OK signal

- CMakeLists.txt
- Makefile.am
- api/dafka_proto.api
- include/dafka_proto.h
- project.xml
- src/Makemodule.am
- src/dafka_classes.h
- src/dafka_consumer.c
- src/dafka_head_key.c
- src/dafka_head_key.h
- src/dafka_msg_key.c
- src/dafka_msg_key.h
- src/dafka_proto.bnf
- src/dafka_proto.c
- src/dafka_proto.xml
- src/dafka_store.c
- src/dafka_store_reader.c
- src/dafka_store_reader.h
- src/dafka_store_writer.c
- src/dafka_store_writer.h
- src/dafka_util.c
- src/dafka_util.h
And some refactoring of the store into different files.
> Problem: Store don't response to get_heads message

- src/dafka_consumer.c
Solution: Don't send GET_HEADS in that case
> Problem: Requesting HEADS on all partition if only one is unknown

- src/dafka_consumer.c
- src/dafka_store.c
Solution: Remove the store/db directory
> Problem: consumer and store tests don't cleanup after themself

- api/dafka_proto.api
- include/dafka_proto.h
- src/dafka_consumer.c
- src/dafka_proto.bnf
- src/dafka_proto.c
- src/dafka_proto.xml
- src/dafka_store.c
- src/dafka_store_reader.c
- src/dafka_store_writer.c
Solution: Implement welcome messages between store and consumer.
> Problem: Consumer doesn't ask net connected store for heads 

- src/dafka_beacon.c
- src/dafka_tower.c
Solution: Provide a way for a beacon actor to provide his own address to the tower
> Problem: tower ip discovery is not always ideal

- src/dafka_consumer.c
Solution: Wrap the debug message with verbose guard
> Problem: debug message is printed in non verbose mode

- src/dafka_towerd.c
> Problem: Unable to set tower address with cmd options

- src/dafka_producer.c
- src/dafka_proto.c
- src/dafka_store_writer.c
It is actually more than double the performance.
> Performance Improvement

- src/dafka_producer.c
- src/dafka_producer_msg.c
Solution: remove heap allocation
> Problem: producer send is using heap allocation which is too slow

- src/dafka_consumer.c
- src/dafka_perf_store.c
- src/dafka_producer.c
Solution: only allow the production to terminate after all acks received
> Problem: producer might terminate before delivering all messages

- src/dafka_consumer.c
- src/dafka_test_peer.c
- src/dafka_test_peer.h
Solution: Add a test in the consumers selftest to check that the
CONSUMER-HELLO cmd is sent correctly
> Problem: CONSUMER-HELLO cmd is not tested

- Dockerfile
- src/dafka_test_peer.c
Solution: Re-generate from zproject
> Problem: Dockerfile does not need a user

- README.md
Solution: use Markdown syntax.
> Problem: invalid markup syntax in README.md

- features/dafka_producer_protocol.feature
- src/dafka_producer_step_defs.c
Solution: Write a gherkin scenario
> Problem: Producer head messages are not tested

- .gitignore
- README.md
- README.txt
- api/dafka_consumer.api
- api/dafka_proto.api
- include/dafka_consumer.h
- include/dafka_proto.h
- src/dafka_consumer.c
- src/dafka_producer.c
- src/dafka_proto.bnf
- src/dafka_proto.c
- src/dafka_proto.xml
Solution: Remove the address field for ACK message by setting it
explicitly where required
> Problem: Address field is not required for the ACK message
